apiVersion: resource.k8s.io/v1
kind: DeviceClass
metadata:
  name: gpu-admin.nvidia.com
spec:
  selectors:
  - cel:
      expression: device.driver == 'gpu.nvidia.com'
  config:
  - opaque:
      driver: gpu.nvidia.com
      parameters:
        apiVersion: resource.nvidia.com/v1beta1
        kind: GpuConfig
